# Test loop running

name: test loop

on:
  workflow_dispatch:

jobs:
  build_all_notebooks:
    runs-on: ubuntu-latest
    env:
        NOTEBOOKS: |
          (
            "nb-one"
            "nb-two"
          )
    steps:
      - name: run a loop
        shell: bash
        run: |
          array=${{ env.NOTEBOOKS }}
          for item in ${array[*]}; do
            echo item;sleep 1;
          done
