# Test loop running

name: test loop

on:
  workflow_dispatch:

jobs:
  build_all_notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: run a loop
        run: |
          for run in {1..3}; do
            date;sleep 1;
          done
        shell: bash
