# Test a custom github action we've made in a different repository
name: test custom action
on:
  workflow_dispatch:
jobs:
  test_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: olivialynn/olivia-hello-world-action@v1.3
